#This is not working
steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - run
      - deploy
      - shelf-analytics-middleware-sandbox
      - --region=europe-west1
      - --source=.
      - --min-instances=1
      - --max-instances=20
      - --add-cloudsql-instances=panprices:europe-west1:panprices-core-sandbox
    secretEnv: ['FIREBASE_API_KEY', 'DB_NAME', 'DB_USER', 'DB_PASS', 'DB_HOST', 'MAGIC_API_SECRET_KEY', 'JWT_SECRET']

availableSecrets:
  secretManager:
    - versionName: projects/panprices/secrets/firebase_api_key/versions/latest
      env: 'FIREBASE_API_KEY'
    - versionName: projects/panprices/secrets/POSTGRES_SANDBOX_SHELF_ANALYTICS_DB/versions/latest
      env: 'DB_NAME'
    - versionName: projects/panprices/secrets/POSTGRES_SANDBOX_USER/versions/latest
      env: 'DB_USER'
    - versionName: projects/panprices/secrets/POSTGRES_SANDBOX_PASSWORD/versions/latest
      env: 'DB_PASS'
    - versionName: projects/panprices/secrets/POSTGRES_SANDBOX_HOST/versions/latest
      env: 'DB_HOST'
    - versionName: projects/panprices/secrets/MAGIC_API_SECRET_KEY/versions/latest
      env: 'MAGIC_API_SECRET_KEY'
    - versionName: projects/panprices/secrets/SHELF_ANALYTICS_JWT_SECRET/versions/latest
      env: 'JWT_SECRET'